// Copyright 2025 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package spec

import "strings"

// ContinentFor returns the ContinentEnum for a DXCC entity code or country
// name.  Returns Continent{} if the entity code or country is not known.
// ADIF does not define continent boundaries, so the IOTA directory was used to
// determine some edge cases, e.g. Trinidad and Tobago are in SA, Cyprus is in
// AS, Iceland is in EU, Indonesia and Philippines are in AS, Galapagos and
// Easter Islands are in SA.  This generally matches CQ zones, though several
// southern islands are classified with AN rather than SA or AF.
//
// Some geopolitical edge cases are not handled because DXCC entities do not
// perfectly follow continent boundaries.  Yemen is AS although Socotra islands
// are part of Africa, Turkey is AS although Thrace is generally thought of as
// part of Europe, Panama is in NA, and Iceland is in EU despite spanning
// continental plates
func ContinentFor(s string) ContinentEnum {
	switch strings.ToUpper(s) {
	default:
		return ContinentEnum{}

	case // AF: Africa
		CountryAgalegaStBrandonIslands.EntityName, CountryAgalegaStBrandonIslands.EntityCode,
		CountryAldabra_deleted.EntityName, CountryAldabra_deleted.EntityCode,
		CountryAlgeria.EntityName, CountryAlgeria.EntityCode,
		CountryAmsterdamStPaulIslands.EntityName, CountryAmsterdamStPaulIslands.EntityCode,
		CountryAngola.EntityName, CountryAngola.EntityCode,
		CountryAnnobonIsland.EntityName, CountryAnnobonIsland.EntityCode,
		CountryAscensionIsland.EntityName, CountryAscensionIsland.EntityCode,
		CountryBenin.EntityName, CountryBenin.EntityCode,
		CountryBlenheimReef_deleted.EntityName, CountryBlenheimReef_deleted.EntityCode,
		CountryBotswana.EntityName, CountryBotswana.EntityCode,
		CountryBritishSomaliland_deleted.EntityName, CountryBritishSomaliland_deleted.EntityCode,
		CountryBurkinaFaso.EntityName, CountryBurkinaFaso.EntityCode,
		CountryBurundi.EntityName, CountryBurundi.EntityCode,
		CountryCameroon.EntityName, CountryCameroon.EntityCode,
		CountryCanaryIslands.EntityName, CountryCanaryIslands.EntityCode,
		CountryCapeVerde.EntityName, CountryCapeVerde.EntityCode,
		CountryCentralAfrica.EntityName, CountryCentralAfrica.EntityCode,
		CountryCeutaMelilla.EntityName, CountryCeutaMelilla.EntityCode,
		CountryChad.EntityName, CountryChad.EntityCode,
		CountryChagosIslands.EntityName, CountryChagosIslands.EntityCode,
		CountryComoros.EntityName, CountryComoros.EntityCode,
		CountryComoros_deleted.EntityName, CountryComoros_deleted.EntityCode,
		CountryCoteDIvoire.EntityName, CountryCoteDIvoire.EntityCode,
		CountryCrozetIsland.EntityName, CountryCrozetIsland.EntityCode,
		CountryDemocraticRepublicOfTheCongo.EntityName, CountryDemocraticRepublicOfTheCongo.EntityCode,
		CountryDesroches_deleted.EntityName, CountryDesroches_deleted.EntityCode,
		CountryDjibouti.EntityName, CountryDjibouti.EntityCode,
		CountryEgypt.EntityName, CountryEgypt.EntityCode,
		CountryEquatorialGuinea.EntityName, CountryEquatorialGuinea.EntityCode,
		CountryEritrea.EntityName, CountryEritrea.EntityCode,
		CountryEthiopia.EntityName, CountryEthiopia.EntityCode,
		CountryFarquhar_deleted.EntityName, CountryFarquhar_deleted.EntityCode,
		CountryFrenchEquatorialAfrica_deleted.EntityName, CountryFrenchEquatorialAfrica_deleted.EntityCode,
		CountryFrenchWestAfrica_deleted.EntityName, CountryFrenchWestAfrica_deleted.EntityCode,
		CountryGabon.EntityName, CountryGabon.EntityCode,
		CountryGeyserReef_deleted.EntityName, CountryGeyserReef_deleted.EntityCode,
		CountryGhana.EntityName, CountryGhana.EntityCode,
		CountryGloriosoIslands.EntityName, CountryGloriosoIslands.EntityCode,
		CountryGoldCoastTogoland_deleted.EntityName, CountryGoldCoastTogoland_deleted.EntityCode,
		CountryGuinea.EntityName, CountryGuinea.EntityCode,
		CountryGuineaBissau.EntityName, CountryGuineaBissau.EntityCode,
		CountryIfni_deleted.EntityName, CountryIfni_deleted.EntityCode,
		CountryItalianSomaliland_deleted.EntityName, CountryItalianSomaliland_deleted.EntityCode,
		CountryJuanDeNovaEuropa.EntityName, CountryJuanDeNovaEuropa.EntityCode,
		CountryKenya.EntityName, CountryKenya.EntityCode,
		CountryKerguelenIslands.EntityName, CountryKerguelenIslands.EntityCode,
		CountryKingdomOfEswatini.EntityName, CountryKingdomOfEswatini.EntityCode,
		CountryLesotho.EntityName, CountryLesotho.EntityCode,
		CountryLiberia.EntityName, CountryLiberia.EntityCode,
		CountryLibya.EntityName, CountryLibya.EntityCode,
		CountryMadagascar.EntityName, CountryMadagascar.EntityCode,
		CountryMadeiraIslands.EntityName, CountryMadeiraIslands.EntityCode,
		CountryMalawi.EntityName, CountryMalawi.EntityCode,
		CountryMali.EntityName, CountryMali.EntityCode,
		CountryMauritania.EntityName, CountryMauritania.EntityCode,
		CountryMauritius.EntityName, CountryMauritius.EntityCode,
		CountryMayotte.EntityName, CountryMayotte.EntityCode,
		CountryMorocco.EntityName, CountryMorocco.EntityCode,
		CountryMozambique.EntityName, CountryMozambique.EntityCode,
		CountryNamibia.EntityName, CountryNamibia.EntityCode,
		CountryNiger.EntityName, CountryNiger.EntityCode,
		CountryNigeria.EntityName, CountryNigeria.EntityCode,
		CountryPenguinIslands_deleted.EntityName, CountryPenguinIslands_deleted.EntityCode,
		CountryPrinceEdwardMarionIslands.EntityName, CountryPrinceEdwardMarionIslands.EntityCode,
		CountryRepublicOfSouthAfrica.EntityName, CountryRepublicOfSouthAfrica.EntityCode,
		CountryRepublicOfTheCongo.EntityName, CountryRepublicOfTheCongo.EntityCode,
		CountryReunionIsland.EntityName, CountryReunionIsland.EntityCode,
		CountryRodriguesIsland.EntityName, CountryRodriguesIsland.EntityCode,
		CountryRuandaUrundi_deleted.EntityName, CountryRuandaUrundi_deleted.EntityCode,
		CountryRwanda.EntityName, CountryRwanda.EntityCode,
		CountrySaoTomePrincipe.EntityName, CountrySaoTomePrincipe.EntityCode,
		CountrySenegal.EntityName, CountrySenegal.EntityCode,
		CountrySeychelles.EntityName, CountrySeychelles.EntityCode,
		CountrySierraLeone.EntityName, CountrySierraLeone.EntityCode,
		CountrySomalia.EntityName, CountrySomalia.EntityCode,
		CountrySouthSudanRepublicOf.EntityName, CountrySouthSudanRepublicOf.EntityCode,
		CountrySouthernSudan_deleted.EntityName, CountrySouthernSudan_deleted.EntityCode,
		CountryStHelena.EntityName, CountryStHelena.EntityCode,
		CountrySudan.EntityName, CountrySudan.EntityCode,
		CountryTangier_deleted.EntityName, CountryTangier_deleted.EntityCode,
		CountryTanzania.EntityName, CountryTanzania.EntityCode,
		CountryTheGambia.EntityName, CountryTheGambia.EntityCode,
		CountryTogo.EntityName, CountryTogo.EntityCode,
		CountryTristanDaCunhaGoughIsland.EntityName, CountryTristanDaCunhaGoughIsland.EntityCode,
		CountryTromelinIsland.EntityName, CountryTromelinIsland.EntityCode,
		CountryTunisia.EntityName, CountryTunisia.EntityCode,
		CountryUganda.EntityName, CountryUganda.EntityCode,
		CountryWalvisBay_deleted.EntityName, CountryWalvisBay_deleted.EntityCode,
		CountryWesternSahara.EntityName, CountryWesternSahara.EntityCode,
		CountryZambia.EntityName, CountryZambia.EntityCode,
		CountryZanzibar_deleted.EntityName, CountryZanzibar_deleted.EntityCode,
		CountryZimbabwe.EntityName, CountryZimbabwe.EntityCode:
		return ContinentAF

	case // AN: Antarctica
		CountryAntarctica.EntityName, CountryAntarctica.EntityCode,
		CountryBouvet.EntityName, CountryBouvet.EntityCode,
		CountryBouvet.EntityName, CountryBouvet.EntityCode,
		CountryHeardIsland.EntityName, CountryHeardIsland.EntityCode,
		CountryMacquarieIsland.EntityName, CountryMacquarieIsland.EntityCode,
		CountryPeter1Island.EntityName, CountryPeter1Island.EntityCode,
		CountrySouthGeorgiaIsland.EntityName, CountrySouthGeorgiaIsland.EntityCode,
		CountrySouthOrkneyIslands.EntityName, CountrySouthOrkneyIslands.EntityCode,
		CountrySouthSandwichIslands.EntityName, CountrySouthSandwichIslands.EntityCode,
		CountrySouthShetlandIslands.EntityName, CountrySouthShetlandIslands.EntityCode:
		return ContinentAN

	case // AS: Asia
		CountryAbuAilIslands_deleted.EntityName, CountryAbuAilIslands_deleted.EntityCode,
		CountryAfghanistan.EntityName, CountryAfghanistan.EntityCode,
		CountryAndamanNicobarIslands.EntityName, CountryAndamanNicobarIslands.EntityCode,
		CountryArmenia.EntityName, CountryArmenia.EntityCode,
		CountryAsiaticRussia.EntityName, CountryAsiaticRussia.EntityCode,
		CountryAzerbaijan.EntityName, CountryAzerbaijan.EntityCode,
		CountryBahrain.EntityName, CountryBahrain.EntityCode,
		CountryBangladesh.EntityName, CountryBangladesh.EntityCode,
		CountryBhutan.EntityName, CountryBhutan.EntityCode,
		CountryBulgaria.EntityName, CountryBulgaria.EntityCode,
		CountryCambodia.EntityName, CountryCambodia.EntityCode,
		CountryChina.EntityName, CountryChina.EntityCode,
		CountryCrete.EntityName, CountryCrete.EntityCode,
		CountryCyprus.EntityName, CountryCyprus.EntityCode,
		CountryDamaoDiu_deleted.EntityName, CountryDamaoDiu_deleted.EntityCode,
		CountryDemocraticPeoplesRepOfKorea.EntityName, CountryDemocraticPeoplesRepOfKorea.EntityCode,
		CountryDodecanese.EntityName, CountryDodecanese.EntityCode,
		CountryFrenchIndia_deleted.EntityName, CountryFrenchIndia_deleted.EntityCode,
		CountryFrenchIndoChina_deleted.EntityName, CountryFrenchIndoChina_deleted.EntityCode,
		CountryGeorgia.EntityName, CountryGeorgia.EntityCode,
		CountryGoa_deleted.EntityName, CountryGoa_deleted.EntityCode,
		CountryGreece.EntityName, CountryGreece.EntityCode,
		CountryHongKong.EntityName, CountryHongKong.EntityCode,
		CountryIndia.EntityName, CountryIndia.EntityCode,
		CountryIran.EntityName, CountryIran.EntityCode,
		CountryIraq.EntityName, CountryIraq.EntityCode,
		CountryIsrael.EntityName, CountryIsrael.EntityCode,
		CountryJapan.EntityName, CountryJapan.EntityCode,
		CountryJordan.EntityName, CountryJordan.EntityCode,
		CountryKamaranIslands_deleted.EntityName, CountryKamaranIslands_deleted.EntityCode,
		CountryKazakhstan.EntityName, CountryKazakhstan.EntityCode,
		CountryKuriaMuriaIsland_deleted.EntityName, CountryKuriaMuriaIsland_deleted.EntityCode,
		CountryKuwait.EntityName, CountryKuwait.EntityCode,
		CountryKuwaitSaudiArabiaNeutralZone_deleted.EntityName, CountryKuwaitSaudiArabiaNeutralZone_deleted.EntityCode,
		CountryKyrgyzstan.EntityName, CountryKyrgyzstan.EntityCode,
		CountryLakshadweepIslands.EntityName, CountryLakshadweepIslands.EntityCode,
		CountryLaos.EntityName, CountryLaos.EntityCode,
		CountryLebanon.EntityName, CountryLebanon.EntityCode,
		CountryMacao.EntityName, CountryMacao.EntityCode,
		CountryMalaya_deleted.EntityName, CountryMalaya_deleted.EntityCode,
		CountryMaldives.EntityName, CountryMaldives.EntityCode,
		CountryManchuria_deleted.EntityName, CountryManchuria_deleted.EntityCode,
		CountryMongolia.EntityName, CountryMongolia.EntityCode,
		CountryMountAthos.EntityName, CountryMountAthos.EntityCode,
		CountryMyanmar.EntityName, CountryMyanmar.EntityCode,
		CountryNepal.EntityName, CountryNepal.EntityCode,
		CountryOgasawara.EntityName, CountryOgasawara.EntityCode,
		CountryOkinawaRyukyuIslands_deleted.EntityName, CountryOkinawaRyukyuIslands_deleted.EntityCode,
		CountryOkinoToriShima_deleted.EntityName, CountryOkinoToriShima_deleted.EntityCode,
		CountryOman.EntityName, CountryOman.EntityCode,
		CountryPakistan.EntityName, CountryPakistan.EntityCode,
		CountryPalestine.EntityName, CountryPalestine.EntityCode,
		CountryPalestine_deleted.EntityName, CountryPalestine_deleted.EntityCode,
		CountryPeoplesDemocraticRepOfYemen_deleted.EntityName, CountryPeoplesDemocraticRepOfYemen_deleted.EntityCode,
		CountryPratasIsland.EntityName, CountryPratasIsland.EntityCode,
		CountryQatar.EntityName, CountryQatar.EntityCode,
		CountryRepublicOfKorea.EntityName, CountryRepublicOfKorea.EntityCode,
		CountryRomania.EntityName, CountryRomania.EntityCode,
		CountrySaudiArabia.EntityName, CountrySaudiArabia.EntityCode,
		CountrySaudiArabiaIraqNeutralZone_deleted.EntityName, CountrySaudiArabiaIraqNeutralZone_deleted.EntityCode,
		CountryScarboroughReef.EntityName, CountryScarboroughReef.EntityCode,
		CountrySikkim_deleted.EntityName, CountrySikkim_deleted.EntityCode,
		CountrySingapore.EntityName, CountrySingapore.EntityCode,
		CountrySpratlyIslands.EntityName, CountrySpratlyIslands.EntityCode,
		CountrySriLanka.EntityName, CountrySriLanka.EntityCode,
		CountrySyria.EntityName, CountrySyria.EntityCode,
		CountryTaiwan.EntityName, CountryTaiwan.EntityCode,
		CountryTajikistan.EntityName, CountryTajikistan.EntityCode,
		CountryThailand.EntityName, CountryThailand.EntityCode,
		CountryTibet_deleted.EntityName, CountryTibet_deleted.EntityCode,
		CountryTurkey.EntityName, CountryTurkey.EntityCode,
		CountryTurkmenistan.EntityName, CountryTurkmenistan.EntityCode,
		CountryUkSovereignBaseAreasOnCyprus.EntityName, CountryUkSovereignBaseAreasOnCyprus.EntityCode,
		CountryUnitedArabEmirates.EntityName, CountryUnitedArabEmirates.EntityCode,
		CountryUzbekistan.EntityName, CountryUzbekistan.EntityCode,
		CountryVietNam.EntityName, CountryVietNam.EntityCode,
		CountryWestMalaysia.EntityName, CountryWestMalaysia.EntityCode,
		CountryYemen.EntityName, CountryYemen.EntityCode,
		CountryYemenArabRepublic_deleted.EntityName, CountryYemenArabRepublic_deleted.EntityCode:
		return ContinentAS

	case // EU: Europe
		CountryAlandIslands.EntityName, CountryAlandIslands.EntityCode,
		CountryAlbania.EntityName, CountryAlbania.EntityCode,
		CountryAndorra.EntityName, CountryAndorra.EntityCode,
		CountryAustria.EntityName, CountryAustria.EntityCode,
		CountryAzores.EntityName, CountryAzores.EntityCode,
		CountryBalearicIslands.EntityName, CountryBalearicIslands.EntityCode,
		CountryBelarus.EntityName, CountryBelarus.EntityCode,
		CountryBelgium.EntityName, CountryBelgium.EntityCode,
		CountryBosniaHerzegovina.EntityName, CountryBosniaHerzegovina.EntityCode,
		CountryCorsica.EntityName, CountryCorsica.EntityCode,
		CountryCroatia.EntityName, CountryCroatia.EntityCode,
		CountryCzechRepublic.EntityName, CountryCzechRepublic.EntityCode,
		CountryCzechoslovakia_deleted.EntityName, CountryCzechoslovakia_deleted.EntityCode,
		CountryDenmark.EntityName, CountryDenmark.EntityCode,
		CountryEngland.EntityName, CountryEngland.EntityCode,
		CountryEstonia.EntityName, CountryEstonia.EntityCode,
		CountryEuropeanRussia.EntityName, CountryEuropeanRussia.EntityCode,
		CountryFaroeIslands.EntityName, CountryFaroeIslands.EntityCode,
		CountryFederalRepublicOfGermany.EntityName, CountryFederalRepublicOfGermany.EntityCode,
		CountryFinland.EntityName, CountryFinland.EntityCode,
		CountryFrance.EntityName, CountryFrance.EntityCode,
		CountryFranzJosefLand.EntityName, CountryFranzJosefLand.EntityCode,
		CountryGermanDemocraticRepublic_deleted.EntityName, CountryGermanDemocraticRepublic_deleted.EntityCode,
		CountryGermany_deleted.EntityName, CountryGermany_deleted.EntityCode,
		CountryGibraltar.EntityName, CountryGibraltar.EntityCode,
		CountryGuernsey.EntityName, CountryGuernsey.EntityCode,
		CountryHungary.EntityName, CountryHungary.EntityCode,
		CountryIceland.EntityName, CountryIceland.EntityCode,
		CountryIreland.EntityName, CountryIreland.EntityCode,
		CountryIsleOfMan.EntityName, CountryIsleOfMan.EntityCode,
		CountryItaly.EntityName, CountryItaly.EntityCode,
		CountryItuHq.EntityName, CountryItuHq.EntityCode,
		CountryJanMayen.EntityName, CountryJanMayen.EntityCode,
		CountryJersey.EntityName, CountryJersey.EntityCode,
		CountryKaliningrad.EntityName, CountryKaliningrad.EntityCode,
		CountryKareloFinnishRepublic_deleted.EntityName, CountryKareloFinnishRepublic_deleted.EntityCode,
		CountryLatvia.EntityName, CountryLatvia.EntityCode,
		CountryLiechtenstein.EntityName, CountryLiechtenstein.EntityCode,
		CountryLithuania.EntityName, CountryLithuania.EntityCode,
		CountryLuxembourg.EntityName, CountryLuxembourg.EntityCode,
		CountryMalta.EntityName, CountryMalta.EntityCode,
		CountryMalyjVysotskijIsland_deleted.EntityName, CountryMalyjVysotskijIsland_deleted.EntityCode,
		CountryMarketReef.EntityName, CountryMarketReef.EntityCode,
		CountryMoldova.EntityName, CountryMoldova.EntityCode,
		CountryMonaco.EntityName, CountryMonaco.EntityCode,
		CountryMontenegro.EntityName, CountryMontenegro.EntityCode,
		CountryNetherlands.EntityName, CountryNetherlands.EntityCode,
		CountryNorthMacedoniaRepublicOf.EntityName, CountryNorthMacedoniaRepublicOf.EntityCode,
		CountryNorthernIreland.EntityName, CountryNorthernIreland.EntityCode,
		CountryNorway.EntityName, CountryNorway.EntityCode,
		CountryPoland.EntityName, CountryPoland.EntityCode,
		CountryPortugal.EntityName, CountryPortugal.EntityCode,
		CountryRepublicOfKosovo.EntityName, CountryRepublicOfKosovo.EntityCode,
		CountrySaar_deleted.EntityName, CountrySaar_deleted.EntityCode,
		CountrySanMarino.EntityName, CountrySanMarino.EntityCode,
		CountrySardinia.EntityName, CountrySardinia.EntityCode,
		CountryScotland.EntityName, CountryScotland.EntityCode,
		CountrySerbia.EntityName, CountrySerbia.EntityCode,
		CountrySlovakRepublic.EntityName, CountrySlovakRepublic.EntityCode,
		CountrySlovenia.EntityName, CountrySlovenia.EntityCode,
		CountrySovereignMilitaryOrderOfMalta.EntityName, CountrySovereignMilitaryOrderOfMalta.EntityCode,
		CountrySpain.EntityName, CountrySpain.EntityCode,
		CountrySvalbard.EntityName, CountrySvalbard.EntityCode,
		CountrySweden.EntityName, CountrySweden.EntityCode,
		CountrySwitzerland.EntityName, CountrySwitzerland.EntityCode,
		CountryTrieste_deleted.EntityName, CountryTrieste_deleted.EntityCode,
		CountryUkraine.EntityName, CountryUkraine.EntityCode,
		CountryVatican.EntityName, CountryVatican.EntityCode,
		CountryWales.EntityName, CountryWales.EntityCode:
		return ContinentEU

	case // NA: North America
		CountryAlaska.EntityName, CountryAlaska.EntityCode,
		CountryAnguilla.EntityName, CountryAnguilla.EntityCode,
		CountryAntiguaBarbuda.EntityName, CountryAntiguaBarbuda.EntityCode,
		CountryAvesIsland.EntityName, CountryAvesIsland.EntityCode,
		CountryBahamas.EntityName, CountryBahamas.EntityCode,
		CountryBajoNuevo_deleted.EntityName, CountryBajoNuevo_deleted.EntityCode,
		CountryBarbados.EntityName, CountryBarbados.EntityCode,
		CountryBelize.EntityName, CountryBelize.EntityCode,
		CountryBermuda.EntityName, CountryBermuda.EntityCode,
		CountryBritishVirginIslands.EntityName, CountryBritishVirginIslands.EntityCode,
		CountryCanada.EntityName, CountryCanada.EntityCode,
		CountryCanalZone_deleted.EntityName, CountryCanalZone_deleted.EntityCode,
		CountryCaymanIslands.EntityName, CountryCaymanIslands.EntityCode,
		CountryClippertonIsland.EntityName, CountryClippertonIsland.EntityCode,
		CountryCocosIsland.EntityName, CountryCocosIsland.EntityCode,
		CountryCostaRica.EntityName, CountryCostaRica.EntityCode,
		CountryCuba.EntityName, CountryCuba.EntityCode,
		CountryDesecheoIsland.EntityName, CountryDesecheoIsland.EntityCode,
		CountryDominica.EntityName, CountryDominica.EntityCode,
		CountryDominicanRepublic.EntityName, CountryDominicanRepublic.EntityCode,
		CountryElSalvador.EntityName, CountryElSalvador.EntityCode,
		CountryGreenland.EntityName, CountryGreenland.EntityCode,
		CountryGrenada.EntityName, CountryGrenada.EntityCode,
		CountryGuadeloupe.EntityName, CountryGuadeloupe.EntityCode,
		CountryGuantanamoBay.EntityName, CountryGuantanamoBay.EntityCode,
		CountryGuatemala.EntityName, CountryGuatemala.EntityCode,
		CountryHaiti.EntityName, CountryHaiti.EntityCode,
		CountryHonduras.EntityName, CountryHonduras.EntityCode,
		CountryJamaica.EntityName, CountryJamaica.EntityCode,
		CountryMartinique.EntityName, CountryMartinique.EntityCode,
		CountryMexico.EntityName, CountryMexico.EntityCode,
		CountryMontserrat.EntityName, CountryMontserrat.EntityCode,
		CountryNavassaIsland.EntityName, CountryNavassaIsland.EntityCode,
		CountryNewfoundlandLabrador_deleted.EntityName, CountryNewfoundlandLabrador_deleted.EntityCode,
		CountryNicaragua.EntityName, CountryNicaragua.EntityCode,
		CountryPanama.EntityName, CountryPanama.EntityCode,
		CountryPuertoRico.EntityName, CountryPuertoRico.EntityCode,
		CountryRevillagigedo.EntityName, CountryRevillagigedo.EntityCode,
		CountrySabaStEustatius.EntityName, CountrySabaStEustatius.EntityCode,
		CountrySableIsland.EntityName, CountrySableIsland.EntityCode,
		CountrySaintBarthelemy.EntityName, CountrySaintBarthelemy.EntityCode,
		CountrySaintMartin.EntityName, CountrySaintMartin.EntityCode,
		CountrySanAndresProvidencia.EntityName, CountrySanAndresProvidencia.EntityCode,
		CountrySerranaBankRoncadorCay_deleted.EntityName, CountrySerranaBankRoncadorCay_deleted.EntityCode,
		CountrySintMaarten.EntityName, CountrySintMaarten.EntityCode,
		CountryStKittsNevis.EntityName, CountryStKittsNevis.EntityCode,
		CountryStLucia.EntityName, CountryStLucia.EntityCode,
		CountryStMaartenSabaStEustatius_deleted.EntityName, CountryStMaartenSabaStEustatius_deleted.EntityCode,
		CountryStPaulIsland.EntityName, CountryStPaulIsland.EntityCode,
		CountryStPierreMiquelon.EntityName, CountryStPierreMiquelon.EntityCode,
		CountryStVincent.EntityName, CountryStVincent.EntityCode,
		CountrySwanIslands_deleted.EntityName, CountrySwanIslands_deleted.EntityCode,
		CountryTurksCaicosIslands.EntityName, CountryTurksCaicosIslands.EntityCode,
		CountryUnitedNationsHq.EntityName, CountryUnitedNationsHq.EntityCode,
		CountryUnitedStatesOfAmerica.EntityName, CountryUnitedStatesOfAmerica.EntityCode,
		CountryVirginIslands.EntityName, CountryVirginIslands.EntityCode:
		return ContinentNA

	case // OC: Oceania
		CountryAmericanSamoa.EntityName, CountryAmericanSamoa.EntityCode,
		CountryAustralIsland.EntityName, CountryAustralIsland.EntityCode,
		CountryAustralia.EntityName, CountryAustralia.EntityCode,
		CountryBakerHowlandIslands.EntityName, CountryBakerHowlandIslands.EntityCode,
		CountryBanabaIslandOceanIsland.EntityName, CountryBanabaIslandOceanIsland.EntityCode,
		CountryBritishNorthBorneo_deleted.EntityName, CountryBritishNorthBorneo_deleted.EntityCode,
		CountryBruneiDarussalam.EntityName, CountryBruneiDarussalam.EntityCode,
		CountryCKiribatiBritishPhoenixIslands.EntityName, CountryCKiribatiBritishPhoenixIslands.EntityCode,
		CountryCelebeMoluccaIslands_deleted.EntityName, CountryCelebeMoluccaIslands_deleted.EntityCode,
		CountryChathamIslands.EntityName, CountryChathamIslands.EntityCode,
		CountryChesterfieldIslands.EntityName, CountryChesterfieldIslands.EntityCode,
		CountryChristmasIsland.EntityName, CountryChristmasIsland.EntityCode,
		CountryCocosKeelingIslands.EntityName, CountryCocosKeelingIslands.EntityCode,
		CountryConwayReef.EntityName, CountryConwayReef.EntityCode,
		CountryDucieIsland.EntityName, CountryDucieIsland.EntityCode,
		CountryEKiribatiLineIslands.EntityName, CountryEKiribatiLineIslands.EntityCode,
		CountryEastMalaysia.EntityName, CountryEastMalaysia.EntityCode,
		CountryFiji.EntityName, CountryFiji.EntityCode,
		CountryFrenchPolynesia.EntityName, CountryFrenchPolynesia.EntityCode,
		CountryGuam.EntityName, CountryGuam.EntityCode,
		CountryHawaii.EntityName, CountryHawaii.EntityCode,
		CountryIndonesia.EntityName, CountryIndonesia.EntityCode,
		CountryJava_deleted.EntityName, CountryJava_deleted.EntityCode,
		CountryJohnstonIsland.EntityName, CountryJohnstonIsland.EntityCode,
		CountryKermadecIslands.EntityName, CountryKermadecIslands.EntityCode,
		CountryKingmanReef_deleted.EntityName, CountryKingmanReef_deleted.EntityCode,
		CountryKureIsland.EntityName, CountryKureIsland.EntityCode,
		CountryLordHoweIsland.EntityName, CountryLordHoweIsland.EntityCode,
		CountryMarianaIslands.EntityName, CountryMarianaIslands.EntityCode,
		CountryMarquesasIslands.EntityName, CountryMarquesasIslands.EntityCode,
		CountryMarshallIslands.EntityName, CountryMarshallIslands.EntityCode,
		CountryMellishReef.EntityName, CountryMellishReef.EntityCode,
		CountryMicronesia.EntityName, CountryMicronesia.EntityCode,
		CountryMidwayIsland.EntityName, CountryMidwayIsland.EntityCode,
		CountryMinamiTorishima.EntityName, CountryMinamiTorishima.EntityCode,
		CountryMinervaReef_deleted.EntityName, CountryMinervaReef_deleted.EntityCode,
		CountryNauru.EntityName, CountryNauru.EntityCode,
		CountryNetherlandsBorneo_deleted.EntityName, CountryNetherlandsBorneo_deleted.EntityCode,
		CountryNetherlandsNewGuinea_deleted.EntityName, CountryNetherlandsNewGuinea_deleted.EntityCode,
		CountryNewCaledonia.EntityName, CountryNewCaledonia.EntityCode,
		CountryNewZealand.EntityName, CountryNewZealand.EntityCode,
		CountryNewZealandSubantarcticIslands.EntityName, CountryNewZealandSubantarcticIslands.EntityCode,
		CountryNiue.EntityName, CountryNiue.EntityCode,
		CountryNorfolkIsland.EntityName, CountryNorfolkIsland.EntityCode,
		CountryNorthCookIslands.EntityName, CountryNorthCookIslands.EntityCode,
		CountryPalau.EntityName, CountryPalau.EntityCode,
		CountryPalmyraJarvisIslands.EntityName, CountryPalmyraJarvisIslands.EntityCode,
		CountryPapuaNewGuinea.EntityName, CountryPapuaNewGuinea.EntityCode,
		CountryPapuaTerritory_deleted.EntityName, CountryPapuaTerritory_deleted.EntityCode,
		CountryPhilippines.EntityName, CountryPhilippines.EntityCode,
		CountryPitcairnIsland.EntityName, CountryPitcairnIsland.EntityCode,
		CountryPortugueseTimor_deleted.EntityName, CountryPortugueseTimor_deleted.EntityCode,
		CountryRotumaIsland.EntityName, CountryRotumaIsland.EntityCode,
		CountrySamoa.EntityName, CountrySamoa.EntityCode,
		CountrySarawak_deleted.EntityName, CountrySarawak_deleted.EntityCode,
		CountrySolomonIslands.EntityName, CountrySolomonIslands.EntityCode,
		CountrySouthCookIslands.EntityName, CountrySouthCookIslands.EntityCode,
		CountrySumatra_deleted.EntityName, CountrySumatra_deleted.EntityCode,
		CountrySwainsIsland.EntityName, CountrySwainsIsland.EntityCode,
		CountryTemotuProvince.EntityName, CountryTemotuProvince.EntityCode,
		CountryTerritoryOfNewGuinea_deleted.EntityName, CountryTerritoryOfNewGuinea_deleted.EntityCode,
		CountryTimorLeste.EntityName, CountryTimorLeste.EntityCode,
		CountryTokelauIslands.EntityName, CountryTokelauIslands.EntityCode,
		CountryTonga.EntityName, CountryTonga.EntityCode,
		CountryTuvalu.EntityName, CountryTuvalu.EntityCode,
		CountryVanuatu.EntityName, CountryVanuatu.EntityCode,
		CountryWKiribatiGilbertIslands.EntityName, CountryWKiribatiGilbertIslands.EntityCode,
		CountryWakeIsland.EntityName, CountryWakeIsland.EntityCode,
		CountryWallisFutunaIslands.EntityName, CountryWallisFutunaIslands.EntityCode,
		CountryWillisIsland.EntityName, CountryWillisIsland.EntityCode:
		return ContinentOC

	case // SA: South America
		CountryArgentina.EntityName, CountryArgentina.EntityCode,
		CountryAruba.EntityName, CountryAruba.EntityCode,
		CountryBolivia.EntityName, CountryBolivia.EntityCode,
		CountryBonaire.EntityName, CountryBonaire.EntityCode,
		CountryBonaireCuracao_deleted.EntityName, CountryBonaireCuracao_deleted.EntityCode,
		CountryBrazil.EntityName, CountryBrazil.EntityCode,
		CountryChile.EntityName, CountryChile.EntityCode,
		CountryColombia.EntityName, CountryColombia.EntityCode,
		CountryCuracao.EntityName, CountryCuracao.EntityCode,
		CountryEasterIsland.EntityName, CountryEasterIsland.EntityCode,
		CountryEcuador.EntityName, CountryEcuador.EntityCode,
		CountryFalklandIslands.EntityName, CountryFalklandIslands.EntityCode,
		CountryFernandoDeNoronha.EntityName, CountryFernandoDeNoronha.EntityCode,
		CountryFrenchGuiana.EntityName, CountryFrenchGuiana.EntityCode,
		CountryGalapagosIslands.EntityName, CountryGalapagosIslands.EntityCode,
		CountryGuyana.EntityName, CountryGuyana.EntityCode,
		CountryJuanFernandezIslands.EntityName, CountryJuanFernandezIslands.EntityCode,
		CountryMalpeloIsland.EntityName, CountryMalpeloIsland.EntityCode,
		CountryParaguay.EntityName, CountryParaguay.EntityCode,
		CountryPeru.EntityName, CountryPeru.EntityCode,
		CountrySanFelixSanAmbrosio.EntityName, CountrySanFelixSanAmbrosio.EntityCode,
		CountryStPeterStPaulRocks.EntityName, CountryStPeterStPaulRocks.EntityCode,
		CountrySuriname.EntityName, CountrySuriname.EntityCode,
		CountryTrindadeMartimVazIslands.EntityName, CountryTrindadeMartimVazIslands.EntityCode,
		CountryTrinidadTobago.EntityName, CountryTrinidadTobago.EntityCode,
		CountryUruguay.EntityName, CountryUruguay.EntityCode,
		CountryVenezuela.EntityName, CountryVenezuela.EntityCode:
		return ContinentSA
	}
}
