// Copyright 2023 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// This file was generated by mkspec; DO NOT EDIT
// Source: https://adif.org.uk/314/ADIF_314_released_exports_2022_12_06.zip
// ADIF specification version 3.1.4 Released 2022-12-06T22:03:52Z

package spec

var ADIFVersion = "3.1.4"
