// Code generated by go-enum DO NOT EDIT.
// Version:
// Revision:
// Build Date:
// Built By:

package cmd

import (
	"fmt"
	"strings"
)

const (
	// SigTypeNone is a SigType of type None.
	SigTypeNone SigType = iota
	// SigTypeIOTA is a SigType of type IOTA.
	SigTypeIOTA
	// SigTypePOTA is a SigType of type POTA.
	SigTypePOTA
	// SigTypeSOTA is a SigType of type SOTA.
	SigTypeSOTA
	// SigTypeWWFF is a SigType of type WWFF.
	SigTypeWWFF
)

var ErrInvalidSigType = fmt.Errorf("not a valid SigType, try [%s]", strings.Join(_SigTypeNames, ", "))

const _SigTypeName = "NoneIOTAPOTASOTAWWFF"

var _SigTypeNames = []string{
	_SigTypeName[0:4],
	_SigTypeName[4:8],
	_SigTypeName[8:12],
	_SigTypeName[12:16],
	_SigTypeName[16:20],
}

// SigTypeNames returns a list of possible string values of SigType.
func SigTypeNames() []string {
	tmp := make([]string, len(_SigTypeNames))
	copy(tmp, _SigTypeNames)
	return tmp
}

var _SigTypeMap = map[SigType]string{
	SigTypeNone: _SigTypeName[0:4],
	SigTypeIOTA: _SigTypeName[4:8],
	SigTypePOTA: _SigTypeName[8:12],
	SigTypeSOTA: _SigTypeName[12:16],
	SigTypeWWFF: _SigTypeName[16:20],
}

// String implements the Stringer interface.
func (x SigType) String() string {
	if str, ok := _SigTypeMap[x]; ok {
		return str
	}
	return fmt.Sprintf("SigType(%d)", x)
}

var _SigTypeValue = map[string]SigType{
	_SigTypeName[0:4]:                    SigTypeNone,
	strings.ToLower(_SigTypeName[0:4]):   SigTypeNone,
	_SigTypeName[4:8]:                    SigTypeIOTA,
	strings.ToLower(_SigTypeName[4:8]):   SigTypeIOTA,
	_SigTypeName[8:12]:                   SigTypePOTA,
	strings.ToLower(_SigTypeName[8:12]):  SigTypePOTA,
	_SigTypeName[12:16]:                  SigTypeSOTA,
	strings.ToLower(_SigTypeName[12:16]): SigTypeSOTA,
	_SigTypeName[16:20]:                  SigTypeWWFF,
	strings.ToLower(_SigTypeName[16:20]): SigTypeWWFF,
}

// ParseSigType attempts to convert a string to a SigType.
func ParseSigType(name string) (SigType, error) {
	if x, ok := _SigTypeValue[name]; ok {
		return x, nil
	}
	// Case insensitive parse, do a separate lookup to prevent unnecessary cost of lowercasing a string if we don't need to.
	if x, ok := _SigTypeValue[strings.ToLower(name)]; ok {
		return x, nil
	}
	return SigType(0), fmt.Errorf("%s is %w", name, ErrInvalidSigType)
}

// Set implements the Golang flag.Value interface func.
func (x *SigType) Set(val string) error {
	v, err := ParseSigType(val)
	*x = v
	return err
}

// Get implements the Golang flag.Getter interface func.
func (x *SigType) Get() interface{} {
	return *x
}

// Type implements the github.com/spf13/pFlag Value interface.
func (x *SigType) Type() string {
	return "SigType"
}
