name: Go

on:
  push:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ">=1.18"
          cache: true

      - name: Test
        run: go test ./...
  build:
    needs: test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: ["386", amd64, arm64]
        exclude:
          - goarch: "386"
            goos: darwin

    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ">=1.18"
          cache: true

      - name: Build ${{ matrix.goos }} ${{ matrix.goarch }}
        run: go build -v -o adif-multitool-${{ matrix.goos }}-${{ matrix.goarch}} ./adifmt
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
      # - uses: "marvinpinto/action-automatic-releases@latest"
      #   with:
      #     repo_token: "${{ secrets.GITHUB_TOKEN }}"
      #     automatic_release_tag: "${{ matrix.goos }}-${{ matrix.goarch }}"
      #     prerelease: false
      #     title: "${{ matrix.goos }}-${{ matrix.goarch }}"
      #     files: |
      #       adif-multitool-${{ matrix.goos }}-${{ matrix.goarch }}
